import type { Config } from 'tailwindcss'

const pxToRem = (px: number, base: number = 16): string => `${px / base}rem`

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/features/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontSize: {
        xxs: ['0.5rem', '0.75rem'],
        overline: [pxToRem(10), { lineHeight: '160%', fontWeight: 500 }],
        'caption-s/regular': [pxToRem(12), { lineHeight: '160%', fontWeight: 400 }],
        'caption-s/medium': [pxToRem(12), { lineHeight: '160%', fontWeight: 500 }],
        'caption-s/bold': [pxToRem(12), { lineHeight: '160%', fontWeight: 700 }],
        'caption-m/regular': [pxToRem(14), { lineHeight: '120%', fontWeight: 400 }],
        'caption-m/medium': [pxToRem(14), { lineHeight: '120%', fontWeight: 500 }],
        'caption-m/bold': [pxToRem(14), { lineHeight: '120%', fontWeight: 700 }],
        'subtitle-s/regular': [pxToRem(14), { lineHeight: '160%', fontWeight: 400 }],
        'subtitle-s/medium': [pxToRem(14), { lineHeight: '160%', fontWeight: 500 }],
        'subtitle-s/bold': [pxToRem(14), { lineHeight: '160%', fontWeight: 700 }],
        'subtitle-m/regular': [pxToRem(16), { lineHeight: '160%', fontWeight: 400 }],
        'subtitle-m/medium': [pxToRem(16), { lineHeight: '160%', fontWeight: 500 }],
        'subtitle-m/bold': [pxToRem(16), { lineHeight: '160%', fontWeight: 700 }],
        'body-s': [pxToRem(14), { lineHeight: '160%', fontWeight: 500 }],
        'body-m/regular': [pxToRem(16), { lineHeight: '120%', fontWeight: 400 }],
        'body-m/medium': [pxToRem(16), { lineHeight: '160%', fontWeight: 500 }],
        listitem: [pxToRem(16), { lineHeight: '120%', fontWeight: 700 }],
        button: [pxToRem(16), { lineHeight: '140%', fontWeight: 700 }],
        h5: [pxToRem(18), { lineHeight: '140%', fontWeight: 700 }],
        h4: [pxToRem(20), { lineHeight: '140%', fontWeight: 700 }],
        h3: [pxToRem(22), { lineHeight: '140%', fontWeight: 700 }],
        h2: [pxToRem(24), { lineHeight: '140%', fontWeight: 700 }],
        h1: [pxToRem(26), { lineHeight: '140%', fontWeight: 700 }],
      },
      borderRadius: {
        none: '0px',
        s: pxToRem(4),
        m: pxToRem(8),
        DEFAULT: pxToRem(8),
        l: pxToRem(12),
        xl: pxToRem(16),
        full: pxToRem(120),
      },
      spacing: {
        xs: pxToRem(4),
        s: pxToRem(8),
        m: pxToRem(12),
        l: pxToRem(16),
        xl: pxToRem(24),
        '2xl': pxToRem(32),
        '3xl': pxToRem(48),
        '4xl': pxToRem(64),
      },
      colors: {
        'primary-green': '#06C755',
        'primary-dark-green': '#019F42',
        'black-1st': '#212121',
        'black-2nd': '#606060',
        'sub-5': '#7D8796',
        'sub-4': '#BAC6D3',
        'sub-3': '#DFE3E8',
        'sub-2': '#EDF0F4',
        'sub-1': '#F5F8FB',
        blue: '#3F92F3',
        red: '#FF7676',
        gray: '#F2F2F2',
        bluegreen: '#84E0BF',
        lightblue: '#99D3D3',
        'cetacean-blue': '#091747',
        'ghost-white': '#f6f8fb',
        'roman-silver': '#7d8796',
        'lavender-gray': '#bac6d3',
        'philippine-gray': '#909090',
        'picton-blue': '#51afe6',
        bubbles: '#e4f9fe',
        lotion: '#fcfcfc',
        'chinese-silver': '#c5cbc7',
        'pale-robin-egg-blue': '#99d3d3',
        'columbia-blue': '#bee5d8',
      },
      maxWidth: {
        base: '480px',
      },
    },
  },
  plugins: [],
}
export default config
